# Generated by Django 5.1.1 on 2024-09-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_thickness', models.CharField(max_length=255)),
                ('measure_thickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thicknesses', to='products.measure')),
            ],
            options={
                'verbose_name': 'Thickness',
                'verbose_name_plural': 'Thicknesses',
            },
        ),
    ]
