# Generated by Django 5.1.1 on 2024-09-25 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_thickness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_lenght', models.CharField(max_length=255)),
                ('measure_lenght', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenghts', to='products.measure')),
            ],
            options={
                'verbose_name': 'Length',
                'verbose_name_plural': 'Lengths',
            },
        ),
    ]
