# Generated by Django 5.1.1 on 2024-09-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_side', models.CharField(max_length=255)),
                ('measure_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sides', to='products.measure')),
            ],
            options={
                'verbose_name': 'Side',
                'verbose_name_plural': 'Sides',
            },
        ),
    ]
