# Generated by Django 5.1.1 on 2024-09-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_polygon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Polygon',
                'verbose_name_plural': 'Polygons',
            },
        ),
        migrations.CreateModel(
            name='GroupSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sides', to='products.side')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_sides', to='products.polygon')),
            ],
            options={
                'verbose_name': 'GroupSide',
                'verbose_name_plural': 'GroupSides',
            },
        ),
    ]
