# Generated by Django 5.1.1 on 2024-09-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_polygon_groupside'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_texture', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Texture',
                'verbose_name_plural': 'Textures',
            },
        ),
        migrations.AlterField(
            model_name='polygon',
            name='name_polygon',
            field=models.CharField(default='I', max_length=255),
        ),
    ]
