# Generated by Django 5.1.1 on 2024-09-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_steel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProfileSteel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_profile_steel', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'TypeProfileSteel',
                'verbose_name_plural': 'TypeProfileSteels',
            },
        ),
    ]
