# Generated by Django 5.1.1 on 2024-09-26 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_pro',
        ),
        migrations.AddField(
            model_name='profilesteel',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_steels_product', to='products.product'),
            preserve_default=False,
        ),
    ]
