# Generated by Django 5.1.1 on 2024-09-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productprofilesteel_productwelding_welding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductProfileSteel',
        ),
        migrations.DeleteModel(
            name='ProductWelding',
        ),
        migrations.CreateModel(
            name='ProductsProfileSteel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='ProductsWelding',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
