# Generated by Django 5.1.1 on 2024-11-18 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_total_remove_saledetail_sub_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=4, unique=True)),
                ('serial_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SerieVoucher',
                'verbose_name_plural': 'SerieVouchers',
            },
        ),
        migrations.CreateModel(
            name='TypeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=255, unique=True)),
                ('voucher_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TypeVoucher',
                'verbose_name_plural': 'TypeVoucher s',
            },
        ),
        migrations.CreateModel(
            name='NumerationVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=9)),
                ('serie_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeration_vouchers_serie_voucher', to='sales.serievoucher')),
            ],
            options={
                'verbose_name': 'NumerationVoucher',
                'verbose_name_plural': 'NumerationVouchers',
            },
        ),
        migrations.AddField(
            model_name='serievoucher',
            name='type_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serie_vouchers_type_voucher', to='sales.typevoucher'),
        ),
    ]
