# Generated by Django 5.1.1 on 2024-11-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_serievoucher_typevoucher_numerationvoucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerationvoucher',
            name='number',
            field=models.IntegerField(),
        ),
    ]
