# Generated by Django 4.2 on 2023-11-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=12)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.persona')),
            ],
        ),
    ]
