# Generated by Django 5.1.1 on 2024-11-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
