# Generated by Django 5.1.1 on 2024-11-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_stock_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='dump',
            field=models.BooleanField(default=False),
        ),
    ]
